### ISSUE TITLE
Agregate el gitIgnore asi no te sube todo

### ISSUE THREAD

**Issue by GianottiG** [florchiexco/LaboratorioV#2]
Aca hay un ejemplo https://www.gitignore.io/api/java,gradle,maven,eclipse,intellij

**Comment by florchiexco** [comment]
Para que funcione el gitignore cree un nuevo repo solo de cerveceria
https://github.com/florchiexco/cerveceria/
Tiene basicamente el mismo codigo que este
Lo comento en el drive tambien
